services:
  database:
    container_name: sprocket-database-python-django
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./server/python-django/src/core/database_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=python-django
    ports:
      - "5432:5432"
  api:
    container_name: sprocket-api-python-django
    image: sprocket-python-django
    build: ./server/python-django
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata ./src/fixtures/auth.json --app auth &&
             python manage.py loaddata ./src/fixtures/sprocket.json --app sprocket &&
             python manage.py runserver 0.0.0.0:8080"
    ports:
      - 8080:8080
    env_file:
      - ./server/python-django/env/.env.dev
    depends_on:
      - database
volumes:
  postgres_data:
