services:
  database:
    container_name: sprocket-database-python-flask
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./server/python-flask/src/database_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=python-flask
    ports:
      - "5432:5432"
  api:
    container_name: sprocket-api-python-flask
    image: sprocket-python-flask
    build: ./server/python-flask
    restart: always
    command: >
      sh -c "sleep 10 &&
             python app.py"
    ports:
      - 8080:8080
    env_file:
      - ./server/python-flask/env/.env.dev
    depends_on:
      - database
volumes:
  postgres_data:
