# Generated by Django 4.2.4 on 2023-08-23 19:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprocket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('teeth', models.IntegerField(verbose_name='Teeth')),
                ('pitch_diameter', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pitch diameter')),
                ('outside_diameter', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Outside diameter')),
                ('pitch', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pitch')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'Sprockets',
            },
        ),
        migrations.CreateModel(
            name='SprocketFactory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Factory name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'Sprocket Factories',
            },
        ),
        migrations.CreateModel(
            name='SprocketFactoryProduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('production_actual', models.IntegerField(verbose_name='Actual production')),
                ('production_goal', models.IntegerField(verbose_name='Goal production')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprocket.sprocketfactory', verbose_name='Factory')),
                ('sprocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprocket.sprocket', verbose_name='Sprocket')),
            ],
            options={
                'verbose_name_plural': 'Sprocket Production',
            },
        ),
    ]
